[workspace]

members = [
    "candelabre-examples",
    "candelabre-internal",
    "candelabre-widgets",
    "candelabre-windowing"
]

[patch.crates-io]
#candelabre-windowing = { path = "./candelabre-windowing" }
