[workspace]

members = [
    "candelabre-app",
    "candelabre-examples",
    "candelabre-experiment",
    "candelabre-widgets",
    "candelabre-windowing"
]

[patch.crates-io]
candelabre-windowing = { path = "./candelabre-windowing" }
