[package]
name = "candelabre-widgets"
version = "0.1.0"
authors = ["othelarian <le.maitre.killian@gmail.com>"]
edition = "2018"

[dependencies]
candelabre-windowing = { path = "../candelabre-windowing" }

#nanovg
